import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer";
import ThemeSwitch from "./Themes/ThemeSwitch";
import HeroTheme from "./Themes/HeroTheme";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Konnect App ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
     <html lang="en">
      <body className={inter.className}>
        <main className=" relative dar  w-full ">
          <ThemeSwitch >
          <div className=" w-full">
            <HeroTheme/>
          </div>
          {children}
          <Footer />
          </ThemeSwitch> 
        </main>
      </body>
    </html>

  );
}
